#!/usr/bin/env python3

""" This file is here to merge individual csv files into one file
The csv files in a directory are read.
This assumes they have the same column headers.
Due to these files being generated by the same script this is true,
but this program does no checking to verify this currently. """

import os
import csv

input_path = sys.argv[1]
ouput_file_name = sys.argv[2]

for root, dirs, files in os.wal(input_path):
	for file in files:
		if file.endswith(".csv"):
			
